### ISSUE TITLE
Command to browse locally or launch in browser?

### ISSUE THREAD

**Issue by peterbenjamin-kh** [jreslock/terraform-provider-docs-local#102]
It may be useful to add a `browse` command (e.g. `terraform-provider-docs-local browse`) that browses the repos locally using the user's defined `editor` config setting (or fallback to `$EDITOR` environment variable, if `editor` is unset).

Example:

```yaml
target_dir: terraform-providers  # Optional, defaults to "./terraform-providers"
providers:
  aws:
    repo: hashicorp/terraform-provider-aws
    description: AWS provider for Terraform
    branch: main # Optional, if not set we auto-detect the HEAD branch from the remote
  azurerm:
    repo: hashicorp/terraform-provider-azurerm
    description: Azure provider for Terraform
editor: glow # if empty, then fallback to $EDITOR environment variable
```

Optionally, if the `--web` flag is specified (e.g. `terraform-provider-docs-local browse --web`), then open the URL `https://registry.terraform.io/providers/${PROVIDER_OWNER}/${PROVIDER_NAME}/${PROVIDER_VERSION}/docs` in the browser (a la https://github.com/pkg/browser)
